Madison-Taylor Fortich  
9291000361

Question 1

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Question 2

In [2]:
data = pd.read_csv('Data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
x = data.iloc[:, :-1] # all rows and columns except last column ; features
y = data.iloc[:, -1] # all rows and only last column ; target variable

In [4]:
print(x)
print('')
print(y)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


Question 3

In [5]:
from sklearn.impute import SimpleImputer
fill_missing_values = SimpleImputer(missing_values=np.nan, strategy='mean') #fill with average
fill_missing_values.fit(x.iloc[:, 1:3]) # calculates the mean for each column based on existing data
x.iloc[:, 1:3] = fill_missing_values.transform(x.iloc[:, 1:3]) # applies the imputer

# or 
# X.iloc[:, 1:3] = fill_missing_values.fit_transform(X.iloc[:, 1:3])

print(x)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000


Question 4

① Encode the independent variable

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
np.set_printoptions(precision=1, suppress=True, floatmode='fixed')
print(x)

[[    1.0     0.0     0.0    44.0 72000.0]
 [    0.0     0.0     1.0    27.0 48000.0]
 [    0.0     1.0     0.0    30.0 54000.0]
 [    0.0     0.0     1.0    38.0 61000.0]
 [    0.0     1.0     0.0    40.0 63777.8]
 [    1.0     0.0     0.0    35.0 58000.0]
 [    0.0     0.0     1.0    38.8 52000.0]
 [    1.0     0.0     0.0    48.0 79000.0]
 [    0.0     1.0     0.0    50.0 83000.0]
 [    1.0     0.0     0.0    37.0 67000.0]]


② Encode the dependent variable

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


Question 5

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0) # test size = 0.2 and random state = 0 

In [9]:
print(X_train)

[[    0.0     1.0     0.0    40.0 63777.8]
 [    1.0     0.0     0.0    37.0 67000.0]
 [    0.0     0.0     1.0    27.0 48000.0]
 [    0.0     0.0     1.0    38.8 52000.0]
 [    1.0     0.0     0.0    48.0 79000.0]
 [    0.0     0.0     1.0    38.0 61000.0]
 [    1.0     0.0     0.0    44.0 72000.0]
 [    1.0     0.0     0.0    35.0 58000.0]]


In [10]:
print(X_test)

[[    0.0     1.0     0.0    30.0 54000.0]
 [    0.0     1.0     0.0    50.0 83000.0]]


In [11]:
print(y_train)

[1 1 1 0 1 0 0 1]


In [12]:
print(y_test)

[0 0]


Question 6

In [13]:
np.set_printoptions(precision=15, suppress=True)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [14]:
print(X_train)

[[ 0.000000000000000  1.000000000000000  0.000000000000000
   0.263067573171354  0.123814785483818]
 [ 1.000000000000000  0.000000000000000  0.000000000000000
  -0.253501479601486  0.461756317627886]
 [ 0.000000000000000  0.000000000000000  1.000000000000000
  -1.975398322177619 -1.530933406394029]
 [ 0.000000000000000  0.000000000000000  1.000000000000000
   0.052613514634271 -1.111419780284153]
 [ 1.000000000000000  0.000000000000000  0.000000000000000
   1.640585047232261  1.720297195957516]
 [ 0.000000000000000  0.000000000000000  1.000000000000000
  -0.081311795343873 -0.167514121536930]
 [ 1.000000000000000  0.000000000000000  0.000000000000000
   0.951826310201807  0.986148350265232]
 [ 1.000000000000000  0.000000000000000  0.000000000000000
  -0.597880848116713 -0.482149341119337]]


In [15]:
print(X_test)

[[ 0.000000000000000  1.000000000000000  0.000000000000000
  -1.458829269404780 -0.901662967229214]
 [ 0.000000000000000  1.000000000000000  0.000000000000000
   1.984964415747487  2.139810822067393]]
